services:
    api:
        build: .
        ports:
            - 3000:3000
        depends_on:
            - mongo
        volumes:
            - ./:/api
            - /api/node_modules
        environment:
            - ANIME_API_BASE_URL=${ANIME_API_BASE_URL}
            - MONGO_URI=${MONGO_URI}
            - JWT_SECRET=${JWT_SECRET}
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - data-db:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    mongo-express:
        image: mongo-express
        depends_on:
            - mongo
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
            - MONGO_CONFIG_BASICAUTH=false
volumes:
    data-db:
